from shipment_system.products.fedex.fedex_air_shipment import FedExAirShipment
from shipment_system.products.fedex.fedex_ground_shipment import FedExGroundShipment
from shipment_system.products.fedex.fedex_water_shipment import FedExWaterShipment